//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomewhatGeeky.Arcadia.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SomewhatGeeky.Arcadia.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;arcadiaLibrary&gt;&lt;platformCollection&gt;&lt;commonFileExtensions&gt;&lt;extension&gt;zip&lt;/extension&gt;&lt;extension&gt;bin&lt;/extension&gt;&lt;/commonFileExtensions&gt;&lt;platform name=&quot;3DO Interactive Multiplayer&quot; id=&quot;23&quot;&gt;&lt;otherNames&gt;&lt;name&gt;3DO&lt;/name&gt;&lt;/otherNames&gt;&lt;/platform&gt;&lt;platform name=&quot;Amiga&quot; id=&quot;39&quot; /&gt;&lt;platform name=&quot;Amiga CD32&quot; id=&quot;46&quot; /&gt;&lt;platform name=&quot;Atari 2600&quot; id=&quot;2&quot;&gt;&lt;uniqueFileExtensions&gt;&lt;extension&gt;a26&lt;/extension&gt;&lt;/uniqueFileExtensions&gt;&lt;otherNames&gt;&lt;name&gt;2600&lt;/name&gt;&lt;/otherNames&gt;&lt;/platform&gt;&lt;plat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
    }
}
